name: "Commons template"
description: "Commons template"
inputs:
  var_env:
    description: "Env variable"
    required: true
    default: "dev"
  var_job:
    description: "Actual Job"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/script.sh ${{inputs.var_job}} ${{inputs.var_env}}
      shell: bash
      name: ${{inputs.var_job}} step [${{inputs.var_env}}]
