name: Actions Complete Demo
on:
  workflow_dispatch:

jobs:
  test-job:
    name: "Test Job"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test step"
        shell: bash
        name: Test step

  ### dev jobs
  build-job-dev:
    name: "Build Job [DEV]"
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build step [DEV]
        uses: ./.github/actions/build
        with:
          var_env: dev

  migrate-job-dev:
    name: "Migrate Job [DEV]"
    runs-on: ubuntu-latest
    needs: [build-job-dev, test-job]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Migrate step [DEV]
        uses: ./.github/actions/migrate
        with:
          var_env: dev

  deploy-job-dev:
    name: "Deployment Job [DEV]"
    runs-on: ubuntu-latest
    needs: [build-job-dev, migrate-job-dev]
    steps:
      - run: |
          echo "Deploy step [DEV]"
        shell: bash
        name: Deploy step [DEV]

  ### stage jobs
  init-stage-job:
    name: "Init stage Job"
    runs-on: ubuntu-latest
    needs: build-job-dev
    environment:
      name: hml
    steps:
      - run: |
          echo "Init step [STAGE]"
        shell: bash
        name: Init step [STAGE]

  build-job-stage:
    name: "Build Job [STAGE]"
    runs-on: ubuntu-latest
    needs: init-stage-job
    steps:
      - run: |
          echo "Buid step [STAGE]"
        shell: bash
        name: Build step [STAGE]
