name: Actions Complete Demo
on:
  workflow_dispatch:

jobs:
  test-job:
    name: "Test Job"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test step"
        shell: bash
        name: Test step

  ### dev jobs
  build-job:
    name: "Build Job"
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: |
          echo "Buid step"
        shell: bash
        name: Build step

  migrate-job:
    name: "Migrate Job"
    runs-on: ubuntu-latest
    needs: [build-job, test-job]
    steps:
      - run: |
          echo "Migrate step"
        shell: bash
        name: Migrate step

  deploy-job:
    name: "Deployment Job"
    runs-on: ubuntu-latest
    needs: [build-job, migrate-job]
    steps:
      - run: |
          echo "Deploy step"
        shell: bash
        name: Deploy step

  ### stage jobs
  init-stage-job:
    name: "Init stage Job"
    runs-on: ubuntu-latest
    needs: build-job
    environment:
      name: hml
    steps:
      - run: |
          echo "Init step [STAGE]"
        shell: bash
        name: Init step [STAGE]

  build-job-stage:
    name: "Build Job [STAGE]"
    runs-on: ubuntu-latest
    needs: init-stage-job
    steps:
      - run: |
          echo "Buid step [STAGE]"
        shell: bash
        name: Build step [STAGE]
